#!/usr/bin/env python3
"""
extract_kahuola_ai_ready.py
Extracts and packages key Kahu Ola context files into KahuOla_AI_Ready/
optimized for loading into AnythingLLM as a Gemma 4 knowledge workspace.
"""

import os
import re
import json
import argparse
from datetime import datetime, timezone
from pathlib import Path

CONTEXT_CONTENT = """# Kahu Ola — AI Context Primer for Gemma 4
# Generated by extract_kahuola_ai_ready.py

## System Identity
Kahu Ola ("Guardian of Life") is a civic hazard intelligence platform for Hawaiʻi.
Domain: kahuola.org | Stack: Cloudflare Worker (TypeScript) + GitHub Pages (HTML/JS)
GitHub: nguyenhuulong22/kahuola-web

## 5 Immutable Invariants
I.   Client NEVER calls NASA/NOAA/NWS/EPA/USGS/PacIOOS directly — all via Worker
II.  UI renders under ALL failure conditions — no blank screens ever
III. Parse fail → DROP data, return [], NEVER infer missing fields
IV.  Zero PII — user location stays on device, never transmitted
V.   Estimated perimeter ≠ official — always show disclaimer

## Data Flow
Browser → Cloudflare Worker (kahuola.org/api/*) → NASA FIRMS / NWS / NOAA / EPA / USGS / PacIOOS

## Canonical Hazard Signals
FireSignal | SmokeSignal | Perimeter | FloodSignal | StormSignal | AirQualitySignal | VolcanicSignal

## Production Lock
Never overwrite without explicit request: index.html, live-map.html, privacy.html, support.html

## Deploy Commands
Worker: cd ~/Documents/kahuola-web/worker && npx wrangler deploy
Website: git add . && git commit -m "feat: [desc]" && git push

## P1 Bugs (fix first)
1. npx wrangler deploy — W4-W8 routes not yet live on production
2. "Data format error" red banner on live-map — needs DevTools Console diagnosis

## Key Identifiers
- Facebook Page ID: 1049357994926463
- Telegram Bot: @KahuOlaHazardBot | Chat ID: 6631407344
- Creatomate template: 9011cd64-9c70-4eb9-99e7-315d78f70050
- R2 base URL: https://media.kahuola.org
- YouTube: @KahuOla (UCt5f7TqG9BenwxqC64MSGvg)
"""

# Source file definitions: (relative_path, category)
SOURCE_FILES = [
    # docs subdirectories — scanned dynamically
    ("docs/doctrine", "doctrine"),
    ("docs/architecture", "architecture"),
    ("docs/api", "api"),
    ("docs/runtime", "runtime"),
    ("docs/map", "map"),
    ("docs/ux", "ux"),
    # root files
    ("SYSTEM_INVARIANTS.md", "root"),
    ("PROJECT_HANDOFF_RULES_.md", "root"),
    ("V4_8_MASTER_INDEX.md", "root"),
    ("KAHUOLA_V4_8_PROGRESS.md", "root"),
    ("CURRENT_PRODUCTION_STATUS.md", "root"),
    ("KAHUOLA_AI_SYSTEM_MANIFEST.txt", "root"),
    ("README.md", "root"),
    # worker / web
    ("worker/src/index.ts", "worker"),
    ("web/live-map.html", "web"),
    ("web/index.html", "web"),
]

SECURITY_PATTERNS = [
    (re.compile(r'[A-Z0-9]{32,}'), "potential API key (uppercase alphanum ≥32)"),
    (re.compile(r'sk-[a-zA-Z0-9]+'), "OpenAI-style key (sk-...)"),
    (re.compile(r'Bearer [a-zA-Z0-9\-_]+'), "Bearer token"),
    (re.compile(r'nasa_firms_map_key|airnow_api_key|maptiler', re.IGNORECASE), "known key identifier"),
]

SKIP_DIRS = {"node_modules", ".git", "__pycache__", ".wrangler", "dist", "KahuOla_AI_Ready"}
SKIP_EXTENSIONS = {".env", ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".woff", ".woff2",
                   ".ttf", ".eot", ".pdf", ".zip", ".tar", ".gz", ".bin", ".lock"}


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def safe_filename(category: str, original: str) -> str:
    name = Path(original).name
    name = name.lower().replace(" ", "_")
    ext = Path(name).suffix or ".md"
    stem = Path(name).stem
    return f"{category}_{stem}{ext}"


def strip_html_blocks(content: str, max_lines: int = 150) -> str:
    """Strip <style> blocks entirely and <script> blocks longer than max_lines."""
    # Strip all <style>...</style>
    content = re.sub(r'<style[^>]*>.*?</style>', '<!-- [STYLE BLOCK STRIPPED] -->', content, flags=re.DOTALL | re.IGNORECASE)

    # Strip <script> blocks > max_lines
    def maybe_strip_script(m):
        block = m.group(0)
        if block.count('\n') > max_lines:
            return '<!-- [SCRIPT BLOCK STRIPPED: >{} lines] -->'.format(max_lines)
        return block

    content = re.sub(r'<script[^>]*>.*?</script>', maybe_strip_script, content, flags=re.DOTALL | re.IGNORECASE)
    return content


def strip_commented_code(content: str) -> str:
    """Strip block comments (/* ... */) from TS/JS."""
    content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
    # Strip full-line // comments (keep inline)
    lines = content.splitlines()
    cleaned = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('//'):
            continue
        cleaned.append(line)
    return '\n'.join(cleaned)


def scan_security(content: str, source_path: str):
    warnings = []
    for pattern, label in SECURITY_PATTERNS:
        matches = pattern.findall(content)
        if matches:
            warnings.append(f"{source_path}: {label} ({len(matches)} match(es))")
    return warnings


def redact_security(content: str) -> str:
    for pattern, _ in SECURITY_PATTERNS:
        content = pattern.sub('[REDACTED_KEY]', content)
    return content


def read_file(path: Path, category: str):
    """Read and preprocess a file. Returns (content, was_redacted)."""
    suffix = path.suffix.lower()
    try:
        raw = path.read_text(encoding="utf-8", errors="replace")
    except Exception as e:
        return None, False, str(e)

    if suffix in (".html",):
        raw = strip_html_blocks(raw, max_lines=150)
    elif suffix in (".ts", ".js"):
        raw = strip_commented_code(raw)

    return raw, False, None


def collect_sources(repo_root: Path):
    """Walk SOURCE_FILES and return list of (path, category) pairs."""
    entries = []
    for src, category in SOURCE_FILES:
        full = repo_root / src
        if full.is_dir():
            # Scan directory for .md files
            for md_file in sorted(full.rglob("*.md")):
                # Skip hidden/skipped dirs
                parts = set(md_file.relative_to(repo_root).parts)
                if parts & SKIP_DIRS:
                    continue
                entries.append((md_file, category))
        else:
            entries.append((full, category))
    return entries


def run(repo_root: Path, output_dir: Path, dry_run: bool):
    ts = now_iso()
    print("🔍 Scanning Kahu Ola repository...")

    all_sources = collect_sources(repo_root)
    print(f"📁 Found {len(all_sources)} candidate source paths")

    security_warnings = []
    file_records = []
    output_files = []  # (out_filename, content, record)

    for src_path, category in all_sources:
        rel = str(src_path.relative_to(repo_root)) if src_path.is_relative_to(repo_root) else str(src_path)

        if not src_path.exists():
            file_records.append({
                "filename": safe_filename(category, src_path.name),
                "source_path": rel,
                "chars": 0,
                "category": category,
                "skipped": True,
                "skip_reason": "file not found",
            })
            continue

        if src_path.suffix.lower() in SKIP_EXTENSIONS:
            file_records.append({
                "filename": safe_filename(category, src_path.name),
                "source_path": rel,
                "chars": 0,
                "category": category,
                "skipped": True,
                "skip_reason": "binary/skip extension",
            })
            continue

        content, _, err = read_file(src_path, category)
        if err or content is None:
            file_records.append({
                "filename": safe_filename(category, src_path.name),
                "source_path": rel,
                "chars": 0,
                "category": category,
                "skipped": True,
                "skip_reason": err or "read error",
            })
            continue

        # Security scan
        warns = scan_security(content, rel)
        if warns:
            security_warnings.extend(warns)
            content = redact_security(content)

        out_name = safe_filename(category, src_path.name)
        # Ensure .md extension for output
        if not out_name.endswith(".md"):
            out_name = Path(out_name).stem + ".md"

        header = f"<!-- SOURCE: {rel} -->\n<!-- CATEGORY: {category} -->\n<!-- EXTRACTED: {ts} -->\n\n"
        final_content = header + content

        record = {
            "filename": out_name,
            "source_path": rel,
            "chars": len(final_content),
            "category": category,
            "skipped": False,
        }
        file_records.append(record)
        output_files.append((out_name, final_content, record))

    # Security scan summary
    if security_warnings:
        print(f"⚠️  Security scan: {len(security_warnings)} warning(s) — keys redacted")
        for w in security_warnings:
            print(f"   • {w}")
    else:
        print("🔐 Security scan: clean")

    if dry_run:
        print("\n--- DRY RUN — no files written ---")
        for out_name, content, rec in output_files:
            print(f"  would write → {output_dir.name}/{out_name}  ({rec['chars']:,} chars)")
        skipped = [r for r in file_records if r.get("skipped")]
        if skipped:
            print(f"\n  Skipped ({len(skipped)}):")
            for r in skipped:
                print(f"    skip → {r['source_path']}  [{r.get('skip_reason', '')}]")
        total_chars = sum(r["chars"] for r in file_records)
        written = len(output_files)
        print(f"\n📦 Total (dry-run): {written} files → {output_dir.name}/ ({total_chars:,} chars)")
        print(f"💡 Next step: drag {output_dir.name}/ into AnythingLLM workspace")
        return

    # Write output
    output_dir.mkdir(parents=True, exist_ok=True)

    # Write _CONTEXT.md
    ctx_path = output_dir / "_CONTEXT.md"
    ctx_path.write_text(CONTEXT_CONTENT, encoding="utf-8")
    print(f"✅ Wrote {output_dir.name}/_CONTEXT.md (doctrine primer)")

    # Build manifest
    manifest = {
        "generated_at": ts,
        "total_files": len(output_files),
        "total_chars": sum(r["chars"] for r in file_records if not r.get("skipped")),
        "files": file_records,
        "security_scan": {
            "exposed_keys_found": bool(security_warnings),
            "warnings": security_warnings,
        },
    }

    manifest_path = output_dir / "_MANIFEST.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"✅ Wrote {output_dir.name}/_MANIFEST.json")

    # Write content files
    for out_name, content, rec in output_files:
        out_path = output_dir / out_name
        out_path.write_text(content, encoding="utf-8")
        print(f"✅ Wrote {output_dir.name}/{out_name} ({rec['chars']:,} chars)")

    total_chars = sum(r["chars"] for r in file_records if not r.get("skipped"))
    written = len(output_files)
    print(f"\n📦 Total: {written} files → {output_dir.name}/ ({total_chars:,} chars)")
    print(f"💡 Next step: drag {output_dir.name}/ into AnythingLLM workspace")


def main():
    parser = argparse.ArgumentParser(description="Extract Kahu Ola context for AnythingLLM / Gemma 4")
    parser.add_argument("--root", type=Path, default=Path("."), help="Repo root (default: cwd)")
    parser.add_argument("--output", type=Path, default=None, help="Output folder (default: <root>/KahuOla_AI_Ready)")
    parser.add_argument("--dry-run", action="store_true", help="List files only, no write")
    args = parser.parse_args()

    repo_root = args.root.resolve()
    output_dir = args.output.resolve() if args.output else repo_root / "KahuOla_AI_Ready"

    run(repo_root, output_dir, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
