window.KAHUOLA_LAYERS_CONFIG = {
  portal: {
    storageKey: "kahuola_portal_mode",
    defaultMode: "lite",
    modes: {
      lite: {
        label: "Lite",
        bounds: {
          sw: [18, -161],
          ne: [23, -154],
        },
        initialCenter: [20.85, -156.4],
        initialZoom: 9,
        maxZoom: 14,
        tileOpacity: 0.62,
        maxGeojsonFeatures: 90,
      },
      full: {
        label: "Full",
        bounds: null,
        initialCenter: [20.85, -156.4],
        initialZoom: 9,
        maxZoom: 18,
        tileOpacity: 0.8,
        maxGeojsonFeatures: 240,
      },
    },
  },
  tabs: ["Fire", "Weather", "Air", "Earth", "Ocean", "Satellite"],
  layers: [
    {
      id: "firms",
      tab: "Fire",
      type: "wms",
      endpointUrl: "/api/tiles/wms/firms",
      healthId: "firms",
      workerImplemented: true,
      source: {
        name: "NASA FIRMS",
      },
      latencyHint: "~5-15 min",
      enabledByDefaultLite: true,
      enabledByDefaultFull: true,
      wmsParams: {
        SERVICE: "WMS",
        REQUEST: "GetMap",
        VERSION: "1.3.0",
        LAYERS: "firms:hotspots_24h",
        STYLES: "",
        FORMAT: "image/png",
        TRANSPARENT: "true",
      },
      legend: {
        title: "NASA FIRMS",
        note: "Satellite heat detections support situational awareness, not official fire boundaries.",
        items: [
          { swatch: "linear-gradient(135deg, #ffd166, #f97316)", label: "Heat signal context" },
          { swatch: "linear-gradient(135deg, #fb7185, #9f1239)", label: "Higher-intensity hotspot" },
        ],
      },
    },
    {
      id: "hms",
      tab: "Fire",
      type: "wms",
      endpointUrl: "/api/tiles/wms/hms",
      healthId: "hms",
      workerImplemented: true,
      source: {
        name: "NOAA HMS",
      },
      latencyHint: "~1 hr",
      enabledByDefaultLite: false,
      enabledByDefaultFull: false,
      wmsParams: {
        SERVICE: "WMS",
        REQUEST: "GetMap",
        VERSION: "1.3.0",
        LAYERS: "hms:smoke",
        STYLES: "",
        FORMAT: "image/png",
        TRANSPARENT: "true",
      },
      legend: {
        title: "NOAA HMS Smoke",
        note: "Smoke shading is a broad visual indicator and can lag local ground truth.",
        items: [
          { swatch: "rgba(125, 211, 252, 0.5)", label: "Light smoke" },
          { swatch: "rgba(59, 130, 246, 0.55)", label: "Moderate smoke" },
          { swatch: "rgba(30, 64, 175, 0.62)", label: "Dense smoke" },
        ],
      },
    },
    {
      id: "wfigs",
      tab: "Fire",
      type: "geojson",
      endpointUrl: "/api/tiles/geojson/wfigs",
      healthId: "wfigs",
      workerImplemented: true,
      source: {
        name: "WFIGS",
      },
      latencyHint: "~15-60 min",
      enabledByDefaultLite: false,
      enabledByDefaultFull: false,
      supportsLiteBounds: true,
      legend: {
        title: "WFIGS Incident Feed",
        note: "Point or perimeter geometry depends on the configured upstream response.",
        items: [
          { swatch: "#f59e0b", label: "Incident marker" },
          { swatch: "#7c3aed", label: "Perimeter linework" },
        ],
      },
    },
    {
      id: "raws",
      tab: "Weather",
      type: "geojson",
      endpointUrl: "/api/tiles/geojson/raws",
      healthId: null,
      workerImplemented: false,
      source: {
        name: "RAWS Stations",
      },
      latencyHint: "Unavailable",
      enabledByDefaultLite: false,
      enabledByDefaultFull: false,
      supportsLiteBounds: true,
      legend: {
        title: "RAWS Placeholder",
        note: "This layer is listed for the library but the Worker endpoint is not deployed yet.",
        items: [
          { swatch: "#0ea5a4", label: "Station marker placeholder" },
        ],
      },
    },
    {
      id: "airnow",
      tab: "Air",
      type: "xyz",
      endpointUrl: "/api/tiles/xyz/airnow/{z}/{x}/{y}.png",
      healthId: "airnow",
      workerImplemented: true,
      source: {
        name: "AirNow",
      },
      latencyHint: "~1 hr",
      enabledByDefaultLite: false,
      enabledByDefaultFull: false,
      legend: {
        title: "AirNow AQI",
        note: "AQI colors are display guidance only and should be paired with official alerts.",
        items: [
          { swatch: "#22c55e", label: "Good" },
          { swatch: "#eab308", label: "Moderate" },
          { swatch: "#f97316", label: "Unhealthy for sensitive groups" },
          { swatch: "#dc2626", label: "Unhealthy or worse" },
        ],
      },
    },
    {
      id: "usgs_quakes",
      tab: "Earth",
      type: "geojson",
      endpointUrl: "/api/tiles/geojson/usgs-quakes",
      healthId: null,
      workerImplemented: false,
      source: {
        name: "USGS Earthquakes",
      },
      latencyHint: "Unavailable",
      enabledByDefaultLite: false,
      enabledByDefaultFull: false,
      filterOptions: [2.5, 4.0, 5.0],
      defaultFilterValue: 2.5,
      legend: {
        title: "USGS Placeholder",
        note: "Magnitude filtering is wired in the UI, but this endpoint is not yet deployed.",
        items: [
          { swatch: "#60a5fa", label: "M2.5+" },
          { swatch: "#2563eb", label: "M4.0+" },
          { swatch: "#1d4ed8", label: "M5.0+" },
        ],
      },
    },
    {
      id: "pacioos",
      tab: "Ocean",
      type: "wms",
      endpointUrl: "/api/tiles/wms/pacioos",
      healthId: "pacioos",
      workerImplemented: true,
      source: {
        name: "PacIOOS",
      },
      latencyHint: "~10-60 min",
      enabledByDefaultLite: false,
      enabledByDefaultFull: false,
      wmsParams: {
        SERVICE: "WMS",
        REQUEST: "GetMap",
        VERSION: "1.3.0",
        LAYERS: "pacioos:ocean",
        STYLES: "",
        FORMAT: "image/png",
        TRANSPARENT: "true",
      },
      legend: {
        title: "PacIOOS Ocean",
        note: "Ocean overlays should be treated as context, not navigation instructions.",
        items: [
          { swatch: "linear-gradient(135deg, #67e8f9, #2563eb)", label: "Wave or current intensity" },
          { swatch: "#0f766e", label: "Observation marker" },
        ],
      },
    },
    {
      id: "goes",
      tab: "Satellite",
      type: "wms",
      endpointUrl: "/api/tiles/wms/goes",
      healthId: "goes",
      workerImplemented: true,
      source: {
        name: "NOAA GOES",
      },
      latencyHint: "~5-15 min",
      enabledByDefaultLite: false,
      enabledByDefaultFull: false,
      products: [
        {
          id: "true-color",
          label: "True Color",
          wmsLayer: "goes:true_color",
          legendNote: "Visible-spectrum composite for broad cloud context.",
        },
        {
          id: "fire-temperature",
          label: "Fire Temperature",
          wmsLayer: "goes:fire_temperature",
          legendNote: "Thermal emphasis for fire-adjacent monitoring.",
        },
        {
          id: "smoke",
          label: "Smoke",
          wmsLayer: "goes:smoke",
          legendNote: "Smoke-oriented view to support plume tracking context.",
        },
      ],
      defaultProduct: "true-color",
      wmsParams: {
        SERVICE: "WMS",
        REQUEST: "GetMap",
        VERSION: "1.3.0",
        LAYERS: "goes:true_color",
        STYLES: "",
        FORMAT: "image/png",
        TRANSPARENT: "true",
      },
      legend: {
        title: "NOAA GOES",
        note: "Only one GOES product should be active at a time.",
        items: [
          { swatch: "linear-gradient(135deg, #e2e8f0, #475569)", label: "True Color" },
          { swatch: "linear-gradient(135deg, #f97316, #7f1d1d)", label: "Fire Temperature" },
          { swatch: "linear-gradient(135deg, #cbd5e1, #334155)", label: "Smoke" },
        ],
      },
    },
  ],
  legalNotices: [
    "Transparency Portal: raw upstream open data visualization.",
    "Not an official directive. Follow official emergency alerts.",
  ],
};
