name: kahuola_flutter

description: Placeholder Flutter app for Kahu Ola V4.8

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true